In [153]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [154]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [155]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 34000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 82000.0]
 ['France' 48.0 89000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Indonesia' 45.0 15000.0]
 ['Philippines' 42.0 20000.0]
 ['Uganda' 66.0 10000.0]
 ['Myanmar' 37.0 37600.0]
 ['Zimbabwe' 40.0 45000.0]
 ['Indonesia' 29.0 nan]]


In [156]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No'
 'Yes' 'No' 'No']


In [157]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [158]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 34000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 51542.857142857145]
 ['France' 35.0 58000.0]
 ['Spain' 40.53333333333333 82000.0]
 ['France' 48.0 89000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Indonesia' 45.0 15000.0]
 ['Philippines' 42.0 20000.0]
 ['Uganda' 66.0 10000.0]
 ['Myanmar' 37.0 37600.0]
 ['Zimbabwe' 40.0 45000.0]
 ['Indonesia' 29.0 51542.857142857145]]


In [159]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [160]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 30.0 34000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 40.0 51542.857142857145]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 40.53333333333333 82000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 48.0 89000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 45.0 15000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 42.0 20000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 66.0 10000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 37.0 37600.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 40.0 45000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 29.0 51542.857142857145]]


In [161]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [162]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 1 0 1 0 0]


In [163]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [164]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 40.53333333333333 82000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 45.0 15000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 40.0 51542.857142857145]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 40.0 45000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 29.0 51542.857142857145]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 66.0 10000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 42.0 20000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 58000.0]]


In [165]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 37.0 37600.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 48.0 89000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 30.0 34000.0]]


In [166]:
print(y_train)

[0 1 1 1 0 0 0 1 0 0 1 1]


In [167]:
print(y_test)

[0 1 1 0]


In [168]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [169]:
print(x_train)

[[0.0 0.0 0.0 0.0 -0.30151134457776363 2.2360679774997902
  -0.30151134457776363 -0.30151134457776363 -0.07860102027701238
  1.3425830738753946]
 [0.0 0.0 1.0 0.0 -0.30151134457776363 -0.447213595499958
  -0.30151134457776363 -0.30151134457776363 0.3826779600347966
  -1.4912218840344171]
 [0.0 1.0 0.0 0.0 -0.30151134457776363 -0.447213595499958
  -0.30151134457776363 -0.30151134457776363 -0.13367910747842218
  0.054380052497203075]
 [0.0 0.0 0.0 0.0 -0.30151134457776363 2.2360679774997902
  -0.30151134457776363 -0.30151134457776363 -1.4762074830127911
  -0.09546720327286808]
 [0.0 0.0 0.0 0.0 -0.30151134457776363 -0.447213595499958
  -0.30151134457776363 3.3166247903554 -0.13367910747842218
  -0.2223539924330089]
 [1.0 0.0 0.0 0.0 -0.30151134457776363 -0.447213595499958
  -0.30151134457776363 -0.30151134457776363 0.27940654653215286
  0.9196271100082585]
 [0.0 0.0 1.0 0.0 -0.30151134457776363 -0.447213595499958
  -0.30151134457776363 -0.30151134457776363 -1.2696646560075036
  0.0543800

In [171]:
print(x_test)

[[0.0 0.0 0.0 0.0 -0.30151134457776363 2.2360679774997902
  -0.30151134457776363 -0.30151134457776363 -0.3402219344837097
  0.4543755497544088]
 [0.0 0.0 0.0 1.0 -0.30151134457776363 -0.447213595499958
  -0.30151134457776363 -0.30151134457776363 -0.4434933479863535
  -0.5353414056946896]
 [1.0 0.0 0.0 0.0 -0.30151134457776363 -0.447213595499958
  -0.30151134457776363 -0.30151134457776363 0.6924922005427279
  1.6386522485823898]
 [0.0 1.0 0.0 0.0 -0.30151134457776363 -0.447213595499958
  -0.30151134457776363 -0.30151134457776363 -1.1663932425048598
  -0.6876055526868585]]
